- name: link config.fish
  file:
    src: "{{ role_path }}/files/config.fish"
    dest: "{{ ansible_env.HOME }}/.config/fish/config.fish"
    state: link
    force: yes

- name: Download oh-my-fish
  ansible.builtin.get_url:
    url: https://get.oh-my.fish
    dest: /tmp/oh-my-fish

- name: Download fisher plugin manager
  ansible.builtin.get_url:
    url: https://git.io/fisher
    dest: /tmp/fisher

- name: Install oh my fish
  ansible.builtin.shell: "fish /tmp/oh-my-fish --path=~/.local/share/omf --config=~/.config/omf"
  args:
    executable: /usr/bin/fish
    creates: /home/ian/.config/omf

- name: Install fisher plugin manager
  ansible.builtin.shell: "source /tmp/fisher && fisher install jorgebucaran/fisher"
  args:
    executable: /usr/bin/fish
    creates: /home/ian/.config/fish/functions/fisher.fish
    
- name: Install fzf plugin for fish
  ansible.builtin.shell: "fisher install PatrickF1/fzf.fish"
  args:
    executable: /usr/bin/fish
    creates: /home/ian/.config/fish/functions/fzf.fish

- name: Install bobthefish
  ansible.builtin.shell: "omf install bobthefish"
  args:
    executable: /usr/bin/fish
    creates: /home/ian/.share/omf/themes/bobthefish

- name: Disable right prompt clock in bobthefish
  ansible.builtin.copy:
    dest: "/home/ian/.config/fish/functions/fish_right_prompt.fish"
    content: "function fish_right_prompt; end"
