---
- name: stage0 
  hosts: all
  become: yes
  become_user: root
  roles:
    - stage0
  tags:
    - stage0

- name: base
  hosts: all
  become: yes
  become_user: root
  roles:
    - base

- name: User configuration
  hosts: all
  become: no
  roles:
    - fish

