- name: link Xresources
  file:
    src: "{{ role_path }}/files/Xresources"
    dest: "{{ ansible_env.HOME }}/.Xresources"
    state: link

- name: link inputrc
  file:
    src: "{{ role_path }}/files/inputrc"
    dest: "{{ ansible_env.HOME }}/.inputrc"
    state: link

- name: link inputrc
  file:
    src: "{{ role_path }}/files/Xmodmap"
    dest: "{{ ansible_env.HOME }}/.Xmodmap"
    state: link

- name: link Xprofile
  file:
    src: "{{ role_path }}/files/xprofile"
    dest: "{{ ansible_env.HOME }}/.xprofile"
    state: link

- name: link Xprofile
  file:
    src: "{{ role_path }}/files/aliases"
    dest: "{{ ansible_env.HOME }}/.aliases"
    state: link


- name: install ttf-fira-fonts
  become: true
  ansible.builtin.pacman:
    state: present
    name:
      - ttf-fira-code
