- name: created dirs if not present for kitty
  file:
    state: directory
    path: "{{item}}"
  with_items:
    - "/home/ian/.config/kitty"

- name: link kitty
  file:
    src: "{{ role_path }}/files/kitty.conf"
    dest: "{{ ansible_env.HOME }}/.config/kitty/kitty.conf"
    state: link
