- name: Install additional packages to make things purdy
  become: yes
  become_user: root
  community.general.pacman:
    state: present
    name:
      - dzen2
      - i3-wm
      - i3status
      - rofi
      - dex
      - powerline
      - powerline-fonts
      - dunst

- name: install polybar,rofi,1password
  community.general.pacman:
    name:
      - polybar
      - pinentry-rofi
      - rofi-dmenu
      - rofi-pass
      - 1pass-git
    executable: yay

- name: created dirs if not present
  file:
    state: directory
    path: "{{item}}"
  with_items:
    - "/home/ian/.config/i3"
    - "/home/ian/.config/i3status"
    - "/home/ian/.config/rofi"

- name: link i3 config
  file:
    src: "{{ role_path }}/files/i3config"
    dest: "{{ ansible_env.HOME }}/.config/i3/config"
    state: link

- name: link i3status config
  file:
    src: "{{ role_path }}/files/i3status"
    dest: "{{ ansible_env.HOME }}/.config/i3status/config"
    state: link

- name: link rofi config
  file:
    src: "{{ role_path }}/files/rofi"
    dest: "{{ ansible_env.HOME }}/.config/rofi/config.rasi"
    state: link

