#!/bin/sh

killall -q polybar

while pgrep -u $UID -x polybar > /dev/null; do sleep 1; done

MONITORS=$(xrandr --query | " connected" | cut -d" " -f1)

MONITORS=$MONITORS polybar example;

echo "Started polybar"
