---
- name: Stage0 packages for basic utilities
  community.general.pacman:
    state: present
    name:
      - docker
      - fish
      - jq
      - git
      - go

- name: Create local account
  ansible.builtin.user:
    name: ian
    password: $6$BpBwhQsLt5fMoWBq$5eO2L7zm0HPFW8hD8ycp8VzuBfQ1jwBtctgBiV9FeGhr4iaScVRxME8ACvzkgwnpUNXeMZRUeUv5GW6OuEucI/
    shell: /usr/bin/fish
    groups:
      - wheel
      - docker

- name: Create sudoers.d for wheel group
  copy:
    dest: "/etc/sudoers.d/wheel"
    content: "%wheel ALL=(ALL) NOPASSWD: ALL"

- name: Clone yay
  become: yes
  become_user: ian
  ansible.builtin.git:
    repo: https://aur.archlinux.org/yay.git
    dest: /tmp/yay

- name: Build and Install yay
  become: yes
  become_user: ian
  ansible.builtin.shell:
    chdir: /tmp/yay
    cmd: /usr/bin/makepkg -si --noconfirm --noprogressbar --nocolor
