---
- name: Stage0 packages for basic utilities
  community.general.pacman:
    state: present
    name:
      - docker
      - fish
      - jq
      - git
      - go

- name: Create local account
  ansible.builtin.user:
    name: ian
    password: $6$BpBwhQsLt5fMoWBq$5eO2L7zm0HPFW8hD8ycp8VzuBfQ1jwBtctgBiV9FeGhr4iaScVRxME8ACvzkgwnpUNXeMZRUeUv5GW6OuEucI/
    shell: /usr/bin/fish
    groups:
      - wheel
      - docker
      - libvirt

- name: Create sudoers.d for wheel group
  copy:
    dest: "/etc/sudoers.d/wheel"
    content: "%wheel ALL=(ALL) NOPASSWD: ALL"

- name: Clone yay
  become: yes
  become_user: ian
  ansible.builtin.git:
    repo: https://aur.archlinux.org/yay.git
    dest: /tmp/yay
    accept_hostkey: yes

- name: Build and Install yay
  become: yes
  become_user: ian
  ansible.builtin.shell:
    chdir: /tmp/yay
    cmd: /usr/bin/makepkg -si --noconfirm --noprogressbar --nocolor

- name: Load github keys
  ansible.builtin.include_vars:
    file: vars/github.yml

- name: Setup SSH dir and perms
  become: yes
  become_user: ian
  ansible.builtin.file:
    state: directory
    path: "{{local_home}}/.ssh"
    mode: '0700'
    owner: "{{ local_user }}"
  vars:
    local_home: "/home/ian"
    local_user: ian

- shell: echo {{github_ssh_private}} |base64 --decode
  register: github_private_key_decoded

- name: Setup SSH keys
  become: yes
  become_user: ian
  ansible.builtin.template:
    src: "{{item.source}}"
    dest: "{{item.dest}}"
    mode: "{{item.mode}}"
    owner: "{{local_user}}"
    backup: "{{item.backup}}"
  vars:
    local_home: "/home/ian"
    local_user: ian
  with_items:
    - {source: "templates/HOME_.ssh_config", dest: "{{local_home}}/.ssh/config", mode: '0644', backup: "yes"}
    - {source: "templates/github.priv", dest: "{{local_home}}/.ssh/github.priv", mode: '0600', backup: "no"}
    - {source: "templates/github.pub", dest: "{{local_home}}/.ssh/github.pub", mode: '0644', backup: "no"}

- name: Clone our own repo
  become: yes
  become_user: ian
  ansible.builtin.git:
    repo: git@github.com:ianand0204/dev-vm.git
    dest: /home/ian/dev-vm
    accept_hostkey: yes


