---
- name: Install some packages
  community.general.pacman:
    state: present
    name:
      - fzf
      - go
      - alacritty
      - i3-wm
      - i3status
      - lightdm
      - lightdm-gtk-greeter
      - gtkmm3
      - open-vm-tools
      - rofi
      - xclip
      - xorg
      - xorg-server

- name: Enable some services
  ansible.builtin.systemd:
    name: lightdm
    enabled: yes

