---
- name: Install some packages
  become: yes
  become_user: root
  community.general.pacman:
    state: present
    name:
      - bat
      - fd
      - fzf
      - firefox
      - go
      - kitty
      - gtkmm3
      - open-vm-tools
      - reflector
      - wget
      - xclip
      - xorg
      - xorg-server

- name: Disable PC Speaker
  become: yes
  become_user: root
  ansible.builtin.copy:
    dest: "/etc/modprobe.d/nobeep.conf"
    content: "blacklist pcspkr"

- name: Install autojump-fish
  community.general.pacman:
    name: autojump
    executable: yay

- name: Copy reflector config to dest
  become: yes
  ansible.builtin.copy:
    dest: "/etc/xdg/reflector/reflector.conf"
    src: "{{ role_path }}/files/reflector.conf"
    force: true

- name: enable reflector
  become: yes
  ansible.builtin.systemd:
    name: reflector.timer
    enabled: true
    state: started 
