---
- name: Install some packages
  become: yes
  become_user: root
  community.general.pacman:
    state: present
    name:
      - bat
      - fd
      - fzf
      - go
      - kitty
      - gtkmm3
      - open-vm-tools
      - xclip
      - xorg
      - xorg-server
