---
- name: Install some packages
  become: yes
  become_user: root
  community.general.pacman:
    state: present
    name:
      - bat
      - fd
      - fzf
      - firefox
      - go
      - kitty
      - gtkmm3
      - open-vm-tools
      - wget
      - xclip
      - xorg
      - xorg-server

- name: Disable PC Speaker
  become: yes
  become_user: root
  ansible.builtin.copy:
    dest: "/etc/modprobe.d/nobeep.conf"
    content: "blacklist pcspkr"
