- name: created dirs for neovim
  file:
    state: directory
    path: "{{item}}"
  with_items:
    - "/home/ian/.config/nvim"
    - "/home/ian/.config/nvim/lua"

- name: link configs
  file:
    state: link
    path: "{{item.path}}"
    src: "{{ role_path }}/files/{{item.src}}"
    force: true
  with_items:
    - {src: "init.lua", path: "/home/ian/.config/nvim/init.lua" }
    - {src: "/lua/settings.lua", path: "/home/ian/.config/nvim/lua/settings.lua"}
    - {src: "/lua/colorscheme.lua", path: "/home/ian/.config/nvim/lua/colorscheme.lua"}
    - {src: "/lua/plugins.lua", path: "/home/ian/.config/nvim/lua/plugins.lua"}
    - {src: "/lua/autocommands.lua", path: "/home/ian/.config/nvim/lua/autocommands.lua"}
    - {src: "/lua/lsp.lua", path: "/home/ian/.config/nvim/lua/lsp.lua"}


      #- name: link init.vim for plugin install
      #  file:
      #    src: "{{ role_path }}/files/init.vim"
      #    dest: "{{ ansible_env.HOME }}/.config/nvim/init.vim"
      #    state: link
      #    force: yes

- name: Install nodejs for language server support
  become: true
  ansible.builtin.pacman:
    name:
      - nodejs
      - npm
      - yarn
